# Uses the dependency-graph/sboms REST API to aquire an SPDX SBOM, attest with build provenance, and upload as an artifact.
name: Generate SBOM
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  attestations: write
jobs:
  gen-sbom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Calls the REST API: https://docs.github.com/en/rest/dependency-graph/sboms?apiVersion=2022-11-28
    - uses: advanced-security/generate-sbom-action@v1
      id: gensbom
    - name: Rename SBOM File to spdx- prefix
      run: | 
        mv ${{ steps.gensbom.outputs.fileName }}  spdx-${{ steps.gensbom.outputs.fileName }}  
    - name: Generate artifact attestation - SPDX JSON
      uses: actions/attest-build-provenance@v1
      with:          
        subject-path: spdx-${{ steps.gensbom.outputs.fileName }}    
    - name: Download CycloneDX CLI
      run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/CycloneDX/cyclonedx-cli/releases/latest | jq -r '.tag_name')
          curl -Lo cyclonedx https://github.com/CycloneDX/cyclonedx-cli/releases/download/${LATEST_RELEASE}/cyclonedx-linux-x64
          chmod +x cyclonedx          
    #fixes: https://github.com/CycloneDX/cyclonedx-cli/issues/316 - writes to temp /tmp/fromspdx/spdx-fixed.json
    - name: workaround cyclonedx-cli/issues/316
      run: |
        cat spdx-${{ steps.gensbom.outputs.fileName }} | sed 's/PACKAGE-MANAGER/PACKAGE_MANAGER/g; s/"DESCRIBE"/"DESCRIBES"/g' > /tmp/spdx.json           
    - name: Convert SPDX SBOM to CycloneDX
      run: |
          FILE_NAME="spdx-${{ steps.gensbom.outputs.fileName }}"
          BASENAME=$(basename "$FILE_NAME" .json)
          cdxBASENAME="cdx-${BASENAME}"
          ./cyclonedx convert --input-file /tmp/spdx.json  --output-file "${cdxBASENAME}.json" --input-format spdxjson --output-format json
          ./cyclonedx convert --input-file /tmp/spdx.json  --output-file "${cdxBASENAME}.xml" --input-format spdxjson --output-format xml
    - name: Generate artifact attestation - CDX JSON
      uses: actions/attest-build-provenance@v1
      with:          
        subject-path: cdx.*.json
    - name: Generate artifact attestation - CDX XML
      uses: actions/attest-build-provenance@v1
      with:          
        subject-path: cdx.*.xml
    - uses: actions/upload-artifact@v4
      with:
        name: sboms
        path: |
              spdx.*.json
              cdx.*.json
              cdx.*.xml
        
